name: DeathChest
description: Creates a chest with all drops when you die.
author: KaskadekingDE
version: 1.2-Beta
main: de.KaskadekingDE.DeathChest.Main

commands:
  deathchest:
    description: Main Command
    usage: /deathchest <args>
    aliases: [dc]