name: DeathChest
description: Creates a chest with all drops when you die.
author: KaskadekingDE
version: 2.6
softdepend: [PacketListenerApi,WorldGuard,GriefPrevention,Towny]
main: de.KaskadekingDE.DeathChest.Main

commands:
  deathchest:
    description: Main Command
    usage: /deathchest <args>
    aliases: [dchest]